package de.saxsys.service.epicservice;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;

/**
 * Created by andre.krause on 29.07.2015.
 */
public class InitDatabaseVerticle extends AbstractVerticle{

	public void start(){
		final JDBCClient client = JDBCClient.createShared(vertx, new JsonObject()
				.put("url", "jdbc:hsqldb:file:db/aufgabenDB")
				.put("driver_class", "org.hsqldb.jdbcDriver")
				.put("max_pool_size", 30), "aufgabenDB");

		client.getConnection(conn -> {
			if (conn.failed()) {
				System.err.println(conn.cause().getMessage());
				return;
			}


			conn.result().execute("create sequence u_id_squence", voidAsyncResult -> {
			});
			conn.result().execute("create table userstory(u_id bigint GENERATED BY DEFAULT AS SEQUENCE u_id_squence PRIMARY KEY, u_title varchar(255) NOT NULL, u_description varchar(255), u_priority varchar(255) NOT NULL, u_order int);", res -> {
				if (res.succeeded())
					System.out.println("Erfolgreich!");
				else
					System.out.println(res.cause().getMessage());
			});
			conn.result().execute("create sequence t_id_squence", voidAsyncResult -> {
			});
			conn.result().execute("create table task(t_id bigint GENERATED BY DEFAULT AS SEQUENCE t_id_squence PRIMARY KEY, u_title varchar(255) NOT NULL, u_description varchar(255), u_priority varchar(255) NOT NULL, inCharge varchar(255), t_order int, u_id bigint NOT NULL, FOREIGN KEY(u_id) REFERENCES userstory(u_id) ON DELETE CASCADE);", res->{
				if(!res.succeeded()){
					System.out.println(res.cause().getMessage());
				}
			});
		});
	}
}
