package de.saxsys.gui.controller;

public enum ButtonType {
    USERSTORY_MOVEUP, USERSTORY_MOVEDOWN, USERSTORY_DELETE, USERSTORY_ADDTASK, TASK_MOVEUP, TASK_MOVEDOWN, TASK_MOVERIGHT, TASK_DELETE
}
